name: Daily Birthday Bot

on:
  schedule:
    - cron: '31 18 * * *'   # 6:00 AM IST
  workflow_dispatch:

jobs:
  run-birthday-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run birthday bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          CSV_URL: ${{ secrets.CSV_URL }}
        run: python main.py
